---

- name: purge ntp packages
  apt:
    name="{{ item }}"
    force=yes
    purge=yes
    state=absent
  with_items:
    - ntp
    - ntpdate
  when: remove_ntp

- name: ensure backports apt repo is setup
  apt_repository: >
    repo="deb {{ backports_url }} {{ backports_distribution_release }} main"
    state=present 
    update_cache=yes
  sudo: yes

- name: ensure tlsdate from backports is installed
  apt:
    name=tlsdated
    state=latest
    install_recommends=no
    force=yes
    default_release="{{ backports_distribution_release }}"

- name: ensure tlsdate is running
  service: name=tlsdate state=running
